# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Original: https://github.com/forexample/hunter-simple/blob/master/.travis.yml

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For off screen rendering
      - libegl1-mesa-dev
      - libosmesa6-dev

      # glapi
      - libgl1-mesa-dev

      # xorg-macros: https://github.com/BlueDragonX/xf86-input-mtrack/issues/27#issuecomment-186871891
      - xutils-dev
      - xserver-xorg-dev-lts-trusty

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      - python3-pip

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      #- g++-5
      #- gcc-5

env:
  global:
    - secure: "Yid/uyHiZ/az+HG6y7AoacyMGtfSSPLaZdX2NzAEypx949AwDoyBqQSlmoJVhVgIDFevVVJxRNSzsgqKzQaKPIjW5o0cjO5Agoc6ACJk2cgZF+aFMfR74IsdkUGJemO8oMqLNYa033EekHV5dnF8Ww9IzNkzdoExtfU7lAKKXyYmZ/ORBXpmysPm8GlMpzWXQ5VN1Nibg7lsFz5AP280/t8zBAvFck5C3YKgZhc1uUQVgHhgdKGuUe1FwmI3adN/urh196d680HKiJ9uHz9MglYlb86SvH4NxOxOu3uDzjxVVr8Vhf539HOBrAzPoAe7hAqISp33BRg2vSCv86moAbfsxY9v228b0ZWCixCrtxyOjDDefiXDf8O9ZFn6YTH6xQuNuiQpUDrMgYHuQTFNw1yl9axdWp4jy0w9cA4rV6vodR4fbiKhc7LdnTLsf7IoCK3av5QlfJc7j5A0VKRtGp0CFcJKWMWnhMBa8TWfJ417eKSQ4re9V2aFI8sP+AXdL7faUWmQlR6xsGaSwbsE1/d3evmtOI4e/I9h9JghWbCsNn3Hd+b4NWKV6jjyLsDONRX94b2JK1SwHU3+FNJkHIkxStZ98RDzV6T2b5VTZSAjsGevztJprmlpORS7iiP14uI9ByNfxINVHEjOXJ22MEXdheVWJ5DTJBUmkRAU09A="

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc INSTALL=--strip MESA=ON TEST=--test

    # }

    # OSX {

    # Try to match toolchains from ingenue deep tests to improve cache hits:
    # https://github.com/ingenue/hunter/blob/pkg.opencv/.travis.yml

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=ios-nocodesign-10-3-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install MESA=OFF

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12 INSTALL=--install MESA=OFF

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon INSTALL=--strip MESA=OFF TEST=--test

    # }

before_install:

  # Add '--quiet' to avoid leaking the token to logs
  - git submodule update --init --recursive --quiet

install:
  # Info about OS
  - uname -a

  # Disable autoupdate
  # * https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
  - export HOMEBREW_NO_AUTO_UPDATE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:

  - >
    travis_wait 200 polly.py
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --ios-multiarch --ios-combined
    --fwd HUNTER_CONFIGURATION_TYPES=${CONFIG}
    OGLES_GPGPU_BUILD_TESTS=ON
    OGLES_GPGPU_USE_OSMESA=${MESA}
    GAUZE_ANDROID_USE_EMULATOR=YES
    HUNTER_CONFIGURATION_TYPES=${CONFIG}
    HUNTER_SUPPRESS_LIST_OF_FILES=ON
    --jobs 2
    ${INSTALL} ${TEST}

branches:
  except:
    - /^pr\..*/
